[package]
name = "issue"
version = "0.1.0"
authors = ["Damian Lesiuk <Damian.Lesiuk@sabre.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0"
